linters:
  enable:
    - gofmt
    - gocyclo
    - bidichk
    - decorder
    - dupword
    - errname
    - errorlint
    - godot
    - gosec
    - makezero
    - misspell
    - nilnil
    - noctx
    - bodyclose
    - prealloc
    - predeclared
    - stylecheck
    - tenv
    - unparam
    - whitespace
    - asasalint
    - asciicheck
    - containedctx
    - contextcheck
    - durationcheck
    - gochecknoglobals
    - goconst
    - gocritic
    - nestif
    - nilerr
    - sloglint
    - wrapcheck

linters-settings:
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  wrapcheck:
    ignoreSigRegexps:
      - 'func \(github\.com/labstack/echo/..\.Context\)\.*' # ignore echo.Context methods
output:
  format: colored-line-number
  print-issued-lines: false
  print-linter-name: true
