version: '3.8'

services:
  go-blog:
    build: .
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - ./.data:/app/data
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_bloggy
    ports:
      - "5432:5432"
    volumes:
      - go_bloggy_data:/var/lib/postgresql/data

volumes:
  go_bloggy_data:
