// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	hcaptcha "github.com/kataras/hcaptcha"
	mock "github.com/stretchr/testify/mock"
)

// MockClientInterface is an autogenerated mock type for the ClientInterface type
type MockClientInterface struct {
	mock.Mock
}

// VerifyToken provides a mock function with given fields: tkn
func (_m *MockClientInterface) VerifyToken(tkn string) hcaptcha.Response {
	ret := _m.Called(tkn)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 hcaptcha.Response
	if rf, ok := ret.Get(0).(func(string) hcaptcha.Response); ok {
		r0 = rf(tkn)
	} else {
		r0 = ret.Get(0).(hcaptcha.Response)
	}

	return r0
}

// NewMockClientInterface creates a new instance of MockClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientInterface {
	mock := &MockClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
