// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ConfirmSubscriberRequest defines model for ConfirmSubscriberRequest.
type ConfirmSubscriberRequest struct {
	// Token The confirmation token
	Token string `json:"token"`
}

// CreateSubscriberRequest defines model for CreateSubscriberRequest.
type CreateSubscriberRequest struct {
	// Captcha The captcha token
	Captcha string `json:"captcha"`
	Email   string `json:"email"`
}

// GitHubAuthRequestBody defines model for GitHubAuthRequestBody.
type GitHubAuthRequestBody struct {
	Code string `json:"code"`
}

// HealthCheckResponse defines model for HealthCheckResponse.
type HealthCheckResponse struct {
	Status string `json:"status"`
}

// JWTToken defines model for JWTToken.
type JWTToken struct {
	Token string `json:"token"`
}

// PostRequest A post object to be created
type PostRequest struct {
	Content string `json:"content"`

	// Description A short description of the post for the index page
	Description string `json:"description"`

	// Keywords Keywords for the post for SEO and search purposes
	Keywords *[]string `json:"keywords,omitempty"`

	// Slug The URL slug of the post. Should be unique and URL-friendly.
	Slug  string `json:"slug"`
	Title string `json:"title"`
}

// PostResponse A post object after it's been created or fetched
type PostResponse struct {
	Content     string    `json:"content"`
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
	Id          int       `json:"id"`
	Keywords    *[]string `json:"keywords,omitempty"`

	// ReadingTime Approximate post reading time in seconds
	ReadingTime int       `json:"reading_time"`
	Slug        string    `json:"slug"`
	Title       string    `json:"title"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// PostsListItem defines model for PostsListItem.
type PostsListItem struct {
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
	Keywords    *[]string `json:"keywords,omitempty"`

	// ReadingTime Approximate post reading time in seconds
	ReadingTime int    `json:"reading_time"`
	Slug        string `json:"slug"`
	Title       string `json:"title"`
}

// PostsListResponse A list of posts
type PostsListResponse struct {
	Posts []PostsListItem `json:"posts"`
	Total int             `json:"total"`
}

// PutPostRequest A post object to be updated
type PutPostRequest struct {
	Content string `json:"content"`

	// Description A short description of the post for the index page
	Description string `json:"description"`

	// Keywords Keywords for the post for SEO and search purposes
	Keywords *[]string `json:"keywords,omitempty"`
	Title    string    `json:"title"`
}

// RequestError defines model for RequestError.
type RequestError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// UnsubscribeRequest defines model for UnsubscribeRequest.
type UnsubscribeRequest struct {
	// Reason The reason for unsubscribing. Optional, do not plan to save it in DB, only for logging purposes.
	Reason         *string `json:"reason,omitempty"`
	SubscriptionId string  `json:"subscription_id"`
}

// GetPostsParams defines parameters for GetPosts.
type GetPostsParams struct {
	// Page Page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostLoginGithubAuthorizeJSONRequestBody defines body for PostLoginGithubAuthorize for application/json ContentType.
type PostLoginGithubAuthorizeJSONRequestBody = GitHubAuthRequestBody

// PostPostsJSONRequestBody defines body for PostPosts for application/json ContentType.
type PostPostsJSONRequestBody = PostRequest

// PutPostsSlugJSONRequestBody defines body for PutPostsSlug for application/json ContentType.
type PutPostsSlugJSONRequestBody = PutPostRequest

// DeleteSubscribersJSONRequestBody defines body for DeleteSubscribers for application/json ContentType.
type DeleteSubscribersJSONRequestBody = UnsubscribeRequest

// PostSubscribersJSONRequestBody defines body for PostSubscribers for application/json ContentType.
type PostSubscribersJSONRequestBody = CreateSubscriberRequest

// PostSubscribersConfirmJSONRequestBody defines body for PostSubscribersConfirm for application/json ContentType.
type PostSubscribersConfirmJSONRequestBody = ConfirmSubscriberRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /health)
	GetHealth(ctx echo.Context) error
	// Authorize with GitHub
	// (POST /login/github/authorize)
	PostLoginGithubAuthorize(ctx echo.Context) error
	// Refresh the JWT token
	// (POST /login/refresh)
	PostLoginRefresh(ctx echo.Context) error
	// Get all posts
	// (GET /posts)
	GetPosts(ctx echo.Context, params GetPostsParams) error
	// Create a new post
	// (POST /posts)
	PostPosts(ctx echo.Context) error
	// Get a post by slug
	// (GET /posts/{slug})
	GetPostsSlug(ctx echo.Context, slug string) error
	// Update a post by slug
	// (PUT /posts/{slug})
	PutPostsSlug(ctx echo.Context, slug string) error
	// Send a post by slug via email
	// (POST /posts/{slug}/send-email)
	PostPostsSlugSendEmail(ctx echo.Context, slug string) error
	// Unsubscribe from the blog
	// (DELETE /subscribers)
	DeleteSubscribers(ctx echo.Context) error
	// Create subscriber for the blog
	// (POST /subscribers)
	PostSubscribers(ctx echo.Context) error
	// Confirm subscriber's email
	// (POST /subscribers/confirm)
	PostSubscribersConfirm(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// PostLoginGithubAuthorize converts echo context to params.
func (w *ServerInterfaceWrapper) PostLoginGithubAuthorize(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostLoginGithubAuthorize(ctx)
	return err
}

// PostLoginRefresh converts echo context to params.
func (w *ServerInterfaceWrapper) PostLoginRefresh(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostLoginRefresh(ctx)
	return err
}

// GetPosts converts echo context to params.
func (w *ServerInterfaceWrapper) GetPosts(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPostsParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPosts(ctx, params)
	return err
}

// PostPosts converts echo context to params.
func (w *ServerInterfaceWrapper) PostPosts(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostPosts(ctx)
	return err
}

// GetPostsSlug converts echo context to params.
func (w *ServerInterfaceWrapper) GetPostsSlug(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", ctx.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter slug: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPostsSlug(ctx, slug)
	return err
}

// PutPostsSlug converts echo context to params.
func (w *ServerInterfaceWrapper) PutPostsSlug(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", ctx.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter slug: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutPostsSlug(ctx, slug)
	return err
}

// PostPostsSlugSendEmail converts echo context to params.
func (w *ServerInterfaceWrapper) PostPostsSlugSendEmail(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", ctx.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter slug: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostPostsSlugSendEmail(ctx, slug)
	return err
}

// DeleteSubscribers converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteSubscribers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteSubscribers(ctx)
	return err
}

// PostSubscribers converts echo context to params.
func (w *ServerInterfaceWrapper) PostSubscribers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostSubscribers(ctx)
	return err
}

// PostSubscribersConfirm converts echo context to params.
func (w *ServerInterfaceWrapper) PostSubscribersConfirm(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostSubscribersConfirm(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/health", wrapper.GetHealth)
	router.POST(baseURL+"/login/github/authorize", wrapper.PostLoginGithubAuthorize)
	router.POST(baseURL+"/login/refresh", wrapper.PostLoginRefresh)
	router.GET(baseURL+"/posts", wrapper.GetPosts)
	router.POST(baseURL+"/posts", wrapper.PostPosts)
	router.GET(baseURL+"/posts/:slug", wrapper.GetPostsSlug)
	router.PUT(baseURL+"/posts/:slug", wrapper.PutPostsSlug)
	router.POST(baseURL+"/posts/:slug/send-email", wrapper.PostPostsSlugSendEmail)
	router.DELETE(baseURL+"/subscribers", wrapper.DeleteSubscribers)
	router.POST(baseURL+"/subscribers", wrapper.PostSubscribers)
	router.POST(baseURL+"/subscribers/confirm", wrapper.PostSubscribersConfirm)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaa2/cNtb+K3yZF8h+0NycyzYDFLuJ6zrjuHbgy3axSeFyxDMSa4pUSMr2JJj/viB1",
	"GV0oj53ajosNEDgaieQ55Hmec5O+4FAmqRQgjMbTL1iHMSTEXW5LsWAqOc7mOlRsDuoIPmWgjX2WKpmC",
	"MgzcSCPPQdgLCnZoapgUeIpPYkBhvgixt1A+LsBwRZKUA57iydaz5y9e/v2HV2MyDykscIDNMrVPtFFM",
	"RHi1CrCCTxlTQPH0QyHqt2qYnP8BocGrAG8rIAZuoG1IUhPGpEff/OFXqRpgSAjjduH1tOLqn8X/w1Am",
	"GzeZLxNUmvq2u8vM22z+OjNxsdE3ki49m5UUmgrd+sjdEj4V3gLhJt6OITw/Ap1KoaGrgDbEZLqpwuG7",
	"jUKLaT6xe7+enJSA68Fh7fiXe/F8N2SHbG92+nk2OWAzPRNHL8Lt2cvZefrvf23vvRoOh38Cd++lNjWs",
	"NSH1GqVSG5SPRkaiOaDQAZXioGMqYUCYpv5PnjxBb4FzGaBLqTj9v4/CB7yG1K4SOpbKoNpdJBfIxJBr",
	"t5DK/WCCwhVKSQQN4J/ETCOmUbJEC6a0cZN8SpzD8lIqqrsavCueVKIqucc7h4gIijQQFcYozVQqNWgc",
	"YGYgaeLmA44kJyLCAZYpCJKymkHWahQ3iFJkaX9rnkV+sp8e7SP7tH4aQ3Qcy4xTa6lMsE8ZOP1Oj/YH",
	"C8VAUL4cNo4nWQ7csQz6jsUww1sc/OX6o2xjzy1QbKRp66BCTT8018y8DptkYUAhZp5qNAcQJUqRVGgB",
	"JozvGLDF8mekNX1rvDUZjH8YjCcn4/HU/fsPDvBC2hiCp5gSAwPDErgBC74Cwow2Jk6qIUwYiEC1YX5n",
	"IFVAKBPRmdta11RpquQVS4gpqFMMR3Y4YgJpCKWgug7MV2Of8iUZ7hW/Ac5SetfmbZGCWTzeiBmtw21g",
	"r6FpH4X0PtNmZiDxhNfHCePvEL1LF9sPn2sRc53n5cx63oVTTncca363brv/V7CwznW0ztZHRao+akLU",
	"YzgjDeGb/FrrQErF8rnefWbm1qlPQbbvqc8DpT53xoub5xwFHnaUkuom5QjYgWfuvmdDCWhtjdKY4tZG",
	"5aMblS/rlXw6nwpdlo29VaMComVPkZs/c0bNqqWYiIbo0A0jPEBUIiENSjmxdTDS5AIQM9Yx/vQmQFLw",
	"pZvPZRRZr1mioZlrzhCV4qlBl0Q4SikIgV0AcgWjRkQsE6m8B1lo5dQ5a2U5VUk4sDXhwBaFA3trcKsy",
	"sS2he9B2BhMLWTKehO6cBbHxBB+TBO3KzwmxCMsUx1McG5Pq6WgUMRNnc1s6jzRJIjdoFMnB3J7WsuME",
	"LOuZ3Rr6mI3HWy8RZ1FsLsH+RXMSnoOg7rApXAC3RtZPkf1rLYXsopaEnIVQeO9Cw19mJ2i/uHs7FUdz",
	"LuejhDAx2p9t7xwc79TYiXcleuOGodfvZzjAF6B0vpHxcDyc2KEl6af42XAyHFsHSkzsgDmKXRluLyPw",
	"+GFXnyOWOz0N6sKm+RplqXM+KhOClX5FuTbNjFqdwOTlvYt/eSBz4rbG45bHJmnKWeimjv4oOJLHpk2R",
	"y9dAcChp7uDwnQObzpKEqCWeFo0HFNqJ7tGIy4iJwggjkplYKvYZyljaPZSdqzAmIgJEUN5IQdZNoL8t",
	"lEysFT6K3Z0T9LvHurkkaWWsBf0j5AyEOWP0xxxyCihTEJqzTLEff/8oLNoI2vv1JG8suUjWPHAbS/ft",
	"2rtO1utqDznLag2eOzl6f/to1SS1URms7tH+VSenx+gBfn6H0hqRySPxDaGodP9O9LMHE/2zVHNGKQjk",
	"wmHJ1kznXLWBg3AuL4Far0/CELR2IwhNmEApEcBbHKkAhC6ZiQuU18miYKFAx/0cOcoHODkVcq1qrkkA",
	"V6kDSYBjIBSUA0cplPizsZP6SriNtKB2mOvY9AaIAuU8+bMwJ4+9hHo1NXdjPBFq1cuyYnP4fxfdkwcT",
	"fSoqR0lvAfAWoL1wzAFd1UveALgLbvGq1uoEuvdlEUYUScA4LH9or/KeRIBElswd0Ji99SkDtcRBmR4U",
	"1cP6zCgsSMaNK7cSJliSJT2lV1vYgZNjKxVXCtjkpCxOfJI5S5jxi94aBzghV7nsrRcbFPntHunQrYsf",
	"Hy8agGviZhX0uMn8vRMiSMBlWVT1u0SRcd5WwaLZDns4v+hziyUL7iPbqDcKbpRjTO5YdD/itou3Md/d",
	"8UZ3bNV89WBqbkux4Cw0TRVd94RwBYQuEVwxR80Gbbt8XMeI0RfNs2h1fajIZcyXqGgG+uPFcf7w2pjR",
	"946pdOO2hlt78UJcP/nbLL5vb/2IHbUV/fzBRB9Ig36WmaAeLFIJWjw1ORZ9EaQJJxtGMg/yTl1ntAu+",
	"PxlJvjJe9GEwl9lpLrWCSfa4GHIP4azZ+n7gqvkvQM2/SDB7/B7E7xY6AW2kQdBB9fWRP1E9BkHLlYgQ",
	"MhMhJJA3km2eW/XAlUYXjORN5btzRd8uqbWOyG5+p/is6nHF7ElfSUG/R1gfP751Fup0uiS6ykJ1wSGr",
	"cE7BJofrvCvYtOZXzuUa9XI0cDCe98a191TIdaqtyDmX3Sz1J7fCcW3Z+4mEnjdnnmjYwfzz7t4OJNou",
	"NPqmHYBm5M49W80f91pgU39gbeLqTbDXctZj3b/d+j6WvYnxHqnD2mC5DWZo03BUfLjcH06Lz6NrKz7V",
	"qPxy91qbFjPvy7R9n23fxLbj7j6/aTrZDAfFGwiNmLggnNHNRu+30Wq1Wv03AAD//2kxGZ39LgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
