// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// GitHubAuthRequestBody defines model for GitHubAuthRequestBody.
type GitHubAuthRequestBody struct {
	Code string `json:"code"`
}

// HealthCheckResponse defines model for HealthCheckResponse.
type HealthCheckResponse struct {
	Status string `json:"status"`
}

// JWTToken defines model for JWTToken.
type JWTToken struct {
	Token string `json:"token"`
}

// PostRequest A post object to be created
type PostRequest struct {
	Content string `json:"content"`

	// Description A short description of the post for the index page
	Description string `json:"description"`

	// Keywords Keywords for the post for SEO and search purposes
	Keywords *[]string `json:"keywords,omitempty"`

	// Slug The URL slug of the post. Should be unique and URL-friendly.
	Slug  string `json:"slug"`
	Title string `json:"title"`
}

// PostResponse A post object after it's been created or fetched
type PostResponse struct {
	Content     string    `json:"content"`
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
	Id          int       `json:"id"`
	Keywords    *[]string `json:"keywords,omitempty"`

	// ReadingTime Approximate post reading time in seconds
	ReadingTime int       `json:"reading_time"`
	Slug        string    `json:"slug"`
	Title       string    `json:"title"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// PostsListItem defines model for PostsListItem.
type PostsListItem struct {
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
	Keywords    *[]string `json:"keywords,omitempty"`

	// ReadingTime Approximate post reading time in seconds
	ReadingTime int    `json:"reading_time"`
	Slug        string `json:"slug"`
	Title       string `json:"title"`
}

// PostsListResponse A list of posts
type PostsListResponse struct {
	Posts []PostsListItem `json:"posts"`
	Total int             `json:"total"`
}

// PutPostRequest A post object to be updated
type PutPostRequest struct {
	Content string `json:"content"`

	// Description A short description of the post for the index page
	Description string `json:"description"`

	// Keywords Keywords for the post for SEO and search purposes
	Keywords *[]string `json:"keywords,omitempty"`
	Title    string    `json:"title"`
}

// RequestError defines model for RequestError.
type RequestError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// SubscriptionRequest defines model for SubscriptionRequest.
type SubscriptionRequest struct {
	// Captcha The captcha token
	Captcha string `json:"captcha"`
	Email   string `json:"email"`
}

// UnsubscribeRequest defines model for UnsubscribeRequest.
type UnsubscribeRequest struct {
	// Reason The reason for unsubscribing. Optional, do not plan to save it in DB, only for logging purposes.
	Reason         *string `json:"reason,omitempty"`
	SubscriptionId string  `json:"subscription_id"`
}

// GetPostsParams defines parameters for GetPosts.
type GetPostsParams struct {
	// Page Page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostLoginGithubAuthorizeJSONRequestBody defines body for PostLoginGithubAuthorize for application/json ContentType.
type PostLoginGithubAuthorizeJSONRequestBody = GitHubAuthRequestBody

// PostPostsJSONRequestBody defines body for PostPosts for application/json ContentType.
type PostPostsJSONRequestBody = PostRequest

// PutPostsSlugJSONRequestBody defines body for PutPostsSlug for application/json ContentType.
type PutPostsSlugJSONRequestBody = PutPostRequest

// DeleteSubscriptionsJSONRequestBody defines body for DeleteSubscriptions for application/json ContentType.
type DeleteSubscriptionsJSONRequestBody = UnsubscribeRequest

// PostSubscriptionsJSONRequestBody defines body for PostSubscriptions for application/json ContentType.
type PostSubscriptionsJSONRequestBody = SubscriptionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /health)
	GetHealth(ctx echo.Context) error
	// Authorize with GitHub
	// (POST /login/github/authorize)
	PostLoginGithubAuthorize(ctx echo.Context) error
	// Refresh the JWT token
	// (POST /login/refresh)
	PostLoginRefresh(ctx echo.Context) error
	// Get all posts
	// (GET /posts)
	GetPosts(ctx echo.Context, params GetPostsParams) error
	// Create a new post
	// (POST /posts)
	PostPosts(ctx echo.Context) error
	// Get a post by slug
	// (GET /posts/{slug})
	GetPostsSlug(ctx echo.Context, slug string) error
	// Update a post by slug
	// (PUT /posts/{slug})
	PutPostsSlug(ctx echo.Context, slug string) error
	// Send a post by slug via email
	// (POST /posts/{slug}/send-email)
	PostPostsSlugSendEmail(ctx echo.Context, slug string) error
	// Unsubscribe from the blog
	// (DELETE /subscriptions)
	DeleteSubscriptions(ctx echo.Context) error
	// Subscribe to the blog
	// (POST /subscriptions)
	PostSubscriptions(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// PostLoginGithubAuthorize converts echo context to params.
func (w *ServerInterfaceWrapper) PostLoginGithubAuthorize(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostLoginGithubAuthorize(ctx)
	return err
}

// PostLoginRefresh converts echo context to params.
func (w *ServerInterfaceWrapper) PostLoginRefresh(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostLoginRefresh(ctx)
	return err
}

// GetPosts converts echo context to params.
func (w *ServerInterfaceWrapper) GetPosts(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPostsParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPosts(ctx, params)
	return err
}

// PostPosts converts echo context to params.
func (w *ServerInterfaceWrapper) PostPosts(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostPosts(ctx)
	return err
}

// GetPostsSlug converts echo context to params.
func (w *ServerInterfaceWrapper) GetPostsSlug(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", ctx.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter slug: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPostsSlug(ctx, slug)
	return err
}

// PutPostsSlug converts echo context to params.
func (w *ServerInterfaceWrapper) PutPostsSlug(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", ctx.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter slug: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutPostsSlug(ctx, slug)
	return err
}

// PostPostsSlugSendEmail converts echo context to params.
func (w *ServerInterfaceWrapper) PostPostsSlugSendEmail(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", ctx.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter slug: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostPostsSlugSendEmail(ctx, slug)
	return err
}

// DeleteSubscriptions converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteSubscriptions(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteSubscriptions(ctx)
	return err
}

// PostSubscriptions converts echo context to params.
func (w *ServerInterfaceWrapper) PostSubscriptions(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostSubscriptions(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/health", wrapper.GetHealth)
	router.POST(baseURL+"/login/github/authorize", wrapper.PostLoginGithubAuthorize)
	router.POST(baseURL+"/login/refresh", wrapper.PostLoginRefresh)
	router.GET(baseURL+"/posts", wrapper.GetPosts)
	router.POST(baseURL+"/posts", wrapper.PostPosts)
	router.GET(baseURL+"/posts/:slug", wrapper.GetPostsSlug)
	router.PUT(baseURL+"/posts/:slug", wrapper.PutPostsSlug)
	router.POST(baseURL+"/posts/:slug/send-email", wrapper.PostPostsSlugSendEmail)
	router.DELETE(baseURL+"/subscriptions", wrapper.DeleteSubscriptions)
	router.POST(baseURL+"/subscriptions", wrapper.PostSubscriptions)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZ+2/cuBH+V1hegfQH7ct59GLg0MY+n7OOzw786BVNDj5KnJV4pkiFpGxvgv3fC1KP",
	"1YPy42o7PjRAkGwkkjPkfN83w9EXHMk0kwKE0XjzC9ZRAilxP3eZeZuHb3KTHMGnHLTZknRpX2RKZqAM",
	"AzcskhTsv3BF0owD3sSzjecvXr76+/evpySMKCxwgM0ys2+0UUzEeLUKsIJPOVNA8eaHYolf61Ey/B0i",
	"g1cBfguEm2Q7gej8CHQmhYa+A9oQk+u2C4fvbjRaTvOZ3fvl5ESeg+jbMtXjtSlY7iXhbsQO2d789PN8",
	"dsDmei6OXkbb81fz8+zf/9reez0ej2/0p1ja5857qU0ZAmuago4UywyTAm/iNyiT2qBiNDIShYAiBcQA",
	"xUEvVMKAMG3/v/vuO/QWOJcBupSK0798FH1fg7bVvhM6kcqgxlMkF8gkUHi3kMr9hwkKVygjMeCg4cJJ",
	"wjRiGqVLtGBKGzfJ58Q5LC+lorrvwbvyTW2qtnu8c4iIoEgDUVGCslxlUoPGAWYG0jZuPuBYciJiHGCZ",
	"gSAZawRk7Ub5gChFlvb/mudx36WTBNDp0T6yb5unMUbHicw5tZHKBfuUg/Pv9Gh/tFAMBOXLcet40uXI",
	"Hcto6FgMM7zDwZ+vP8ou9twC5UbasQ5q1AxDc83M67BJFgYUYuaZRiGAqFCKpEILMFFyz4Atlz8jnekb",
	"043ZaPr9aDo7mU433Z//4AAvpErtUEyJgZFhKdyCBX8Awoy2Js7qIUwYiEF1YX5vIFVAKBPxmdtaP1RZ",
	"puQVS4kpqVMOR3Y4YgJpiKSgugnM11Of8xUZHhS/Ac4zet/h7ZCCWTzeihmdw21hr+XpEIX0PtNmbiD1",
	"pNenCeNvEL1PiR2Gz7WIuU55ObPKu3DO6Z6wFk+bsfurgoUV18m6HpyUxeCkDVFP4Iw0hN+ka50DqRwr",
	"5nr3mZs7lz4l2b6VPo9U+twbL25fc5R42FFKqttcR8AOPHPPPRtKQWsblNYUtzaqXt3q+rJeyefzcR7W",
	"22vgueM6yUyUEH8lWb5ExTUhuNN1K8CQEsY7x1L8+mf57ziS6Y07LZYJak99Wz0VuthsCIM7VUC0j0x2",
	"o8U7h9+8XoqJeIwO3TDCA0QlEtKgjBNhea/JBSBmbA74cStAUvClm89lHNsEUQG/XVbPEZXimUGXRDj1",
	"UBABuwDkNqkREctUKi9mdCOaZ52Crg7HyMZjZAMyso9Gd7oRdy30D9rOYGIhK3EjkTtnQWzqxMckRbvy",
	"c0osVHLF8SZOjMn05mQSM5PkoQ33RJM0doMmsRyF9rSWPb2zAsfs1tDHfDrdeIU4ixNzCfZvFJLoHAR1",
	"h03hArgNsn6G7N82UsguavWGswjKRFV6+PP8BO2XT+/m4iTkMpykhInJ/nx75+B4pyFEeFeiLTcMvXk/",
	"xwG+AKWLjUzH0/HMDq30bRM/H8/GU5sriEkcMCeJ6zjYnzF4Uo5rRSBW6LsGdWFvNBrlmdNZlQvBKglV",
	"xM6ZU+sTmKKT4VJ9kbOduY3ptJOcSJZxFrmpk99LjhRp+KYk7euVOJS0d3D4zoFN52lK1BJvlj0WFNmJ",
	"7tWEy5iJMggTkptEKvYZqrKhfyg7V1FCRAyIoKJnhKwior8tlExtFD6K3Z0T9JsnuoUlaW2sDf0j4gyE",
	"OWP0hwJyCihTEJmzXLEffvsoLNoI2vvlpBBDl7TbB27Lhn279q6z9abeQ8GyRi/rXo7e3ylbtUltVA6r",
	"B4x/3bQaCHqAX9yjtVYS9ljcIhRV8u9MP3800z9JFTJKQSCX+Su25rrgqk0chHN5CdSqPoki0NqNIDRl",
	"AmVEAO9wpAYQumQmKVHeJIuChQKdDHPkqBjg7NTIta65fghcZQ4kAU6AUFAOHJVR4i88T5or4S7SgsZh",
	"rnPTFhAFyin586ggj/0JzYtj6MZ4MtRqkGXl5vD/L7pnj2b6VNRCSe8A8A6gvXAsAF1fDb0JcBfc4vW1",
	"spfo3lf3TaJICsZh+UN3lfckBiTyNHRAY/bRpxzUEgdVeVBelNZnRmFBcm7czTJlgqV5OnDL7Bo7cHbs",
	"pczdemxxUt3DfJY5S5nxm96YBjglV4XtjZc3OPLrA9Kh3wJ4erxoAa6Nm1UwIJPbrvOBCBJwWd0fhyVR",
	"5Jx3XbBotsMeTxd9slix4CGqjWZP5FY1xuyeTQ8jbrv88PRNjm+UY+vm60dzc1uKBWeRabvoGkWEKyB0",
	"ieCKOWq2aNvn4zpHTL5onser61NFYSNcorLv6c8Xx8XLa3PG0Oe0SsbtHW6t4qW5YfJ3WfzQav2Ehdqa",
	"fvFopg+kQT/JXFAPFqkELZ6ZAou+DNKGk00juQd5p64J3Aff/5hJ/mC+GMJgYbPXXOokk/xpMeQB0lm7",
	"y//It+Y/ATX/JMns6SuIXxZ6CW2iQdBR3TH3F6rHIGi1EhFC5iKCFIpGsq1z6x640uiCkaKpfH9S9PWK",
	"WitEdvM75aeAp5WzZ0NXCvotw/r48bWrUOfTJdF1FapLDlmHCwq2OdzkXcmmNb8KLje/nZSfSzkYz0fy",
	"xpcq5HrV1mjIZb9O/dGtcNxa+GGyoefrmScj9nD/or+7A4m2S4++ahegnb0LdWto8mAMBnsEx/WEEife",
	"kFmxeoyA+b7s3iZiT1SpbgiX/+xXq9XqvwEAAP//8Q8NzEksAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
