package: api
generate:
  echo-server: true
  models: true # Models specify whether to generate type definitions
  embedded-spec: true # Embed the swagger spec into the generated code
output: api.gen.go
