// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/samgozman/go-bloggy/internal/config"
	"github.com/samgozman/go-bloggy/internal/db"
	"github.com/samgozman/go-bloggy/internal/github"
)

// Injectors from wire.go:

func initApp(ctx context.Context, cfg *config.Config) (*tempApp, error) {
	string2 := db.ProvideDSN(cfg)
	database, err := db.ProvideDatabase(string2)
	if err != nil {
		return nil, err
	}
	githubConfig := github.ProvideConfig(cfg)
	service := github.ProvideService(githubConfig)
	mainTempApp := newTempApp(database, service)
	return mainTempApp, nil
}
