// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/samgozman/go-bloggy/internal/captcha"
	"github.com/samgozman/go-bloggy/internal/config"
	"github.com/samgozman/go-bloggy/internal/db"
	"github.com/samgozman/go-bloggy/internal/github"
	"github.com/samgozman/go-bloggy/internal/jwt"
)

// Injectors from wire.go:

func initApp(ctx context.Context, cfg *config.Config) (*tempApp, error) {
	dsn := db.ProvideDSN(cfg)
	database, err := db.ProvideDatabase(dsn)
	if err != nil {
		return nil, err
	}
	githubConfig := github.ProvideConfig(cfg)
	service := github.ProvideService(githubConfig)
	jwtSecretKey := jwt.ProvideJWTSecretKey(cfg)
	jwtService := jwt.ProvideService(jwtSecretKey)
	hCaptchaSecret := captcha.ProvideHCaptchaSecret(cfg)
	client := captcha.ProvideClient(hCaptchaSecret)
	mainTempApp := newTempApp(database, service, jwtService, client)
	return mainTempApp, nil
}
