name: Tests and coverage

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  unit_test_go:
    name: Run tests and coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2

      - name: Set up golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.57.1
          args: --timeout=5m

      - name: Get Go dependencies
        run: go mod download

      - name: Generate code
        run: make generate

      - name: Lint check with golangci-lint
        run: make lint

      - name: Run unit tests with coverage
        run: make test-coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.out
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
